### ISSUE TITLE
手机扫码登陆失败

### ISSUE THREAD

**Issue by skylinehyc** [lvgithub/jd_seckill_new#12]

**Comment by skylinehyc** [comment]
2021-01-19 11:13:12,025 - 604-MainThread - D:\code\test\jd_spider_requests.py[line:212] - INFO: 已完成手机客户端确认
2021-01-19 11:13:12,328 - 604-MainThread - D:\code\test\jd_spider_requests.py[line:235] - INFO: {'returnCode': 80}
Traceback (most recent call last):
  File "D:/code/test/main.py", line 26, in <module>
    jd_seckill.reserve()
  File "D:\code\test\jd_spider_requests.py", line 313, in new_func
    self.login_by_qrcode()
  File "D:\code\test\jd_spider_requests.py", line 297, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "D:\code\test\jd_spider_requests.py", line 262, in login_by_qrcode
    raise SKException('二维码信息校验失败')
exception.SKException: 二维码信息校验失败

**Comment by skylinehyc** [comment]
因为我加了代理。。。。
